### ISSUE TITLE
unclear ref

### ISSUE THREAD

**Issue by maelle** [ropensci-review-tools/ropensci-review-tools#8]
what line is referred to in "after the above line in the editor_check() function. "?

https://ropensci-review-tools.readthedocs.io/en/latest/maintenance/pkgcheck.html

**Comment by maelle** [comment]
also, when removing a check after running pkgcheck, it means it is still run. Is it problematic depending on the duration of that check?

**Comment by mpadge** [comment]
Thanks, that commit revises the entire text there, and hopefully makes it much clearer.
> also, when removing a check after running pkgcheck, it means it is still run. Is it problematic depending on the duration of that check?

Yes, potentially. That's why the section is called "Controlling checks in `roreviewapi`". This is all admittedly quite confusing because the page itself is about maintenance of `pkgcheck`, and not `roreviewapi`. But these maintenance pages are only intended to be relevant to rOpenSci-internal folk for maintenance of the whole check system anyway, so resolving such confusion is relatively low priority for the moment - hopefully that's okay?

Controlling checks within `pkgcheck` itself is a purely package-internal thing, so is documented in the main `pkgcheck docs ... but this is all still very unclear, so i've opened #12. Thanks!

**Comment by maelle** [comment]
:ok_hand:
